investment_periods: [2030, 2040, 2050]

active_model: NL
climate_years: [1995, 2008, 2009]

model_cases:
  DK:
    demand_zones: [DKE1, DKW1]
    capacity_factor_zone: DKW1
  NL:
    demand_zones: [NL00]
    capacity_factor_zone: NL00
  DK_NL:
    regions:
      DK:
        demand_zones: [DKE1, DKW1]
        capacity_factor_zone: DKW1
      NL:
        demand_zones: [NL00]
        capacity_factor_zone: NL00
    interconnectors:
      - name: DK_NL_interconnector
        bus0: DK
        bus1: NL
        capacity_mw: 1000

period_weights:
  2030: 10
  2040: 10
  2050: 10

discount_rate: 0.04

eurdkk: 7.47

gas_price_dkk_per_gj_fuel:
  2030: 80
  2040: 85
  2050: 85

load_shedding:
  variable_cost_eur_per_mwh: 10000
  max_capacity_mw: 1000000

capacity_limits_mw:
  wind: 50000
  solar: 50000
  gas_turbine: 100000
  gas_turbine_cc: 100000
